# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:36


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('url', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('html', models.TextField()),
                ('downloaded', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('repeated', models.BooleanField()),
                ('location', models.CharField(max_length=128)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[(b'room', b'Classroom'), (b'teacher', b'Teacher'), (b'group', b'Group'), (b'student', b'Student')], max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooster.Source'),
        ),
    ]
